### ISSUE TITLE
FilterReg handle large initial translation 

### ISSUE THREAD

**Issue by Ggs1mida** [neka-nat/probreg#78]
Hi:
I am using FilterReg to register two point clouds with about 100m initial translation distance. But I got identity matrix as result. Are there any parameters to be set to limit the search area?

Thanks,
Ningli Xu

**Comment by drlight-code** [comment]
Depending on the size (ca. bounding box diagonal) you could probably choose a very large sigma so that the two point clouds have a chance to attract each other over that distance, however that will also negatively impact your result when they are close, because every point will influence every other with the same weight. 

What keeps you from just pre-registering them by moving their centers of gravity such that they meet at halfway distance, for example?
