### ISSUE TITLE
RigidCPD does not work in multiprocessing.Process

### ISSUE THREAD

**Issue by jwindhager** [neka-nat/probreg#90]
When running `RigidCPD` in a `multiprocessing.Process` (Linux, `start_method="fork"`) without CUDA/cupy available, the process hangs in the following line: 

https://github.com/neka-nat/probreg/blob/21d5ed26583a8077fd1a151c3df8369e2f528fe1/probreg/math_utils.py#L26

Debugging & inspecting the stack trace, this gets called here:

https://github.com/neka-nat/probreg/blob/21d5ed26583a8077fd1a151c3df8369e2f528fe1/probreg/cpd.py#L130

Presumably, the C code does not work with Python's `multiprocessing` module?

**Comment by neka-nat** [comment]
Hi,
The problem is that the c wrapper object cannot be pickle when using multiprocessing.
I don't know if it will work, but the following articles and tools may help.

https://stackoverflow.com/questions/19984152/what-can-multiprocessing-and-dill-do-together
https://pathos.readthedocs.io/en/latest/pathos.html
https://joblib.readthedocs.io/en/latest/auto_examples/serialization_and_wrappers.html

**Comment by jwindhager** [comment]
Thanks a lot for the insight! I worked around the problem by spawning the worker processes instead of forking them.
